# settings
set-option -g allow-rename off # don't rename windows automatically
set -sg escape-time 10 # set wait time after pressing escape
set-window-option -g mode-keys vi # vi mode

# display
set-option default-terminal "screen-256color" # configure true colors

# remaps 

unbind-key r
bind-key r source-file ~/.tmux.conf # reload config

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane

bind -n C-Down select-pane -D # navigate down
bind -n C-Up select-pane -U # navigate up
bind -n C-Left select-pane -L # navigate left
bind -n C-Right select-pane -R # navigate right

