format = """
$directory\
$git_state\
$git_status\
$jobs\
$character"""

[directory]
truncate_to_repo = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[hostname]
format = '$ssh_symbol$hostname\] '
ssh_only = false

[nix_shell]
format = 'via [$symbol$state( \($name\))]($style)'

[username]
format = '\[$user@'
show_always = true
