format = """
$username\
$hostname\
$directory\
$git_state\
$git_status\
$nix_shell"""

[username]
format = '\[$user@'
show_always = true

[hostname]
format = '$ssh_symbol$hostname\] '
ssh_only = false

[nix_shell]
format = '\($name\))]($style)'
